import type { ElephantCampProductProfile } from './types'

const BOOKING_CHANNEL_BASE =
  'https://widgets.bokun.io/online-sales/3f335ed3-148b-4690-b13f-c76a637227db/experience'

const nonChiangMaiCity = 'Bangkok & Pattaya' as ElephantCampProductProfile['city']

export const ownerManagedBokunProfiles: ElephantCampProductProfile[] = [
  {
    source: 'bokun_owner_managed',
    bokunId: '1232729',
    title: 'Half-Day Morning Elephant Sanctuary Program in Chiang Mai',
    campName: 'Living Green Elephant Sanctuary',
    city: 'Chiang Mai',
    category: 'elephant_care',
    durationType: 'half_day',
    kidFriendlyScore: 5,
    ethicalScore: 5,
    elephantInteractionLevel: 4,
    foodOrCookingFocus: false,
    natureFocus: true,
    bathingAvailable: false,
    feedingAvailable: true,
    walkingAvailable: true,
    photoFriendly: true,
    transferConvenienceScore: 3,
    physicalIntensity: 'low',
    bestFor: ['Families', 'First-time elephant sanctuary visitors', 'Half-day morning plans'],
    notIdealFor: ['Bathing is not listed for this experience.'],
    pickupAreas: ['old_city', 'nimman', 'night_bazaar', 'not_sure'],
    priceLevel: 'mid',
    bookingHandoffUrl: `${BOOKING_CHANNEL_BASE}/1232729`,
  },
  {
    source: 'bokun_owner_managed',
    bokunId: '1232731',
    title: 'Half-Day Afternoon Elephant Sanctuary Program in Chiang Mai',
    campName: 'Living Green Elephant Sanctuary',
    city: 'Chiang Mai',
    category: 'elephant_care',
    durationType: 'half_day',
    kidFriendlyScore: 5,
    ethicalScore: 5,
    elephantInteractionLevel: 5,
    foodOrCookingFocus: false,
    natureFocus: true,
    bathingAvailable: true,
    feedingAvailable: true,
    walkingAvailable: true,
    photoFriendly: true,
    transferConvenienceScore: 3,
    physicalIntensity: 'low',
    bestFor: ['Families', 'Afternoon plans', 'Hands-on elephant interaction'],
    notIdealFor: ['Bathing depends on conditions and elephant willingness.'],
    pickupAreas: ['old_city', 'nimman', 'night_bazaar', 'not_sure'],
    priceLevel: 'mid',
    bookingHandoffUrl: `${BOOKING_CHANNEL_BASE}/1232731`,
  },
  {
    source: 'bokun_owner_managed',
    bokunId: '1232733',
    title: 'Full-Day Elephant Sanctuary and Pad Thai Cooking in Chiang Mai',
    campName: 'Living Green Elephant Sanctuary',
    city: 'Chiang Mai',
    category: 'elephant_care',
    durationType: 'full_day',
    kidFriendlyScore: 4,
    ethicalScore: 5,
    elephantInteractionLevel: 5,
    foodOrCookingFocus: true,
    natureFocus: true,
    bathingAvailable: true,
    feedingAvailable: true,
    walkingAvailable: true,
    photoFriendly: true,
    transferConvenienceScore: 3,
    physicalIntensity: 'medium',
    bestFor: ['Full-day elephant care', 'Cooking add-on', 'Hands-on elephant interaction'],
    notIdealFor: ['Bathing depends on conditions and elephant willingness.'],
    pickupAreas: ['old_city', 'nimman', 'night_bazaar', 'not_sure'],
    priceLevel: 'mid',
    bookingHandoffUrl: `${BOOKING_CHANNEL_BASE}/1232733`,
  },
  {
    source: 'bokun_owner_managed',
    bokunId: '1232736',
    title: 'Thai Cooking Class and Ethical Elephant Sanctuary Chiang Mai',
    campName: 'Living Green Elephant Sanctuary',
    city: 'Chiang Mai',
    category: 'cooking_or_food',
    durationType: 'full_day',
    kidFriendlyScore: 4,
    ethicalScore: 5,
    elephantInteractionLevel: 4,
    foodOrCookingFocus: true,
    natureFocus: true,
    bathingAvailable: true,
    feedingAvailable: true,
    walkingAvailable: true,
    photoFriendly: false,
    transferConvenienceScore: 3,
    physicalIntensity: 'medium',
    bestFor: ['Cooking-focused travelers', 'Full-day local experience', 'Ethical elephant care'],
    notIdealFor: ['Bathing depends on elephant willingness.'],
    pickupAreas: ['old_city', 'nimman', 'night_bazaar', 'not_sure'],
    priceLevel: 'mid',
    bookingHandoffUrl: `${BOOKING_CHANNEL_BASE}/1232736`,
  },
  {
    source: 'bokun_owner_managed',
    bokunId: '1232798',
    title: 'Inthanon Heaven Trail(Living Green Elephant Sanctuary)',
    campName: 'Living Green Elephant Sanctuary',
    city: 'Chiang Mai',
    category: 'nature_day_trip',
    durationType: 'full_day',
    kidFriendlyScore: 2,
    ethicalScore: 3,
    elephantInteractionLevel: 1,
    foodOrCookingFocus: false,
    natureFocus: true,
    bathingAvailable: false,
    feedingAvailable: false,
    walkingAvailable: false,
    photoFriendly: false,
    transferConvenienceScore: 3,
    physicalIntensity: 'high',
    bestFor: ['Nature day trips', 'Doi Inthanon plans', 'Active travelers'],
    notIdealFor: ['Hiking-heavy; better for active travelers.'],
    pickupAreas: ['old_city', 'nimman', 'riverside', 'night_bazaar', 'not_sure'],
    priceLevel: 'mid',
    bookingHandoffUrl: `${BOOKING_CHANNEL_BASE}/1232798`,
  },
  {
    source: 'bokun_owner_managed',
    bokunId: '1232799',
    title: 'Living Green Elephant Sanctuary Experience near Bangkok & Pattaya',
    campName: 'Living Green Elephant Sanctuary',
    city: nonChiangMaiCity,
    category: 'elephant_care',
    durationType: 'flexible',
    kidFriendlyScore: 3,
    ethicalScore: 3,
    elephantInteractionLevel: 3,
    foodOrCookingFocus: false,
    natureFocus: false,
    bathingAvailable: false,
    feedingAvailable: false,
    walkingAvailable: false,
    photoFriendly: false,
    transferConvenienceScore: 3,
    physicalIntensity: 'medium',
    bestFor: ['Bangkok or Pattaya travelers'],
    notIdealFor: ['Not a Chiang Mai experience; excluded from Chiang Mai recommendations.'],
    pickupAreas: ['outside_city', 'not_sure'],
    priceLevel: 'mid',
    bookingHandoffUrl: `${BOOKING_CHANNEL_BASE}/1232799`,
  },
  {
    source: 'bokun_owner_managed',
    bokunId: '1236811',
    title: 'Day for Elephant Half-Day Morning-Bigboy',
    campName: 'Big Boy Elephant Sanctuary Chiang Mai',
    city: 'Chiang Mai',
    category: 'elephant_care',
    durationType: 'half_day',
    kidFriendlyScore: 4,
    ethicalScore: 3,
    elephantInteractionLevel: 4,
    foodOrCookingFocus: true,
    natureFocus: true,
    bathingAvailable: false,
    feedingAvailable: true,
    walkingAvailable: false,
    photoFriendly: true,
    transferConvenienceScore: 3,
    physicalIntensity: 'low',
    bestFor: ['Half-day morning plans', 'Families', 'Elephant feeding'],
    notIdealFor: ['Bathing is not listed for this experience.'],
    pickupAreas: ['old_city', 'nimman', 'riverside', 'night_bazaar', 'not_sure'],
    priceLevel: 'mid',
    bookingHandoffUrl: `${BOOKING_CHANNEL_BASE}/1236811`,
  },
  {
    source: 'bokun_owner_managed',
    bokunId: '1236820',
    title: 'Day for Elephant Half-Day Afternoon',
    campName: 'Big Boy Elephant Sanctuary Chiang Mai',
    city: 'Chiang Mai',
    category: 'elephant_care',
    durationType: 'half_day',
    kidFriendlyScore: 4,
    ethicalScore: 3,
    elephantInteractionLevel: 4,
    foodOrCookingFocus: true,
    natureFocus: true,
    bathingAvailable: false,
    feedingAvailable: true,
    walkingAvailable: false,
    photoFriendly: true,
    transferConvenienceScore: 3,
    physicalIntensity: 'low',
    bestFor: ['Half-day afternoon plans', 'Families', 'Elephant feeding'],
    notIdealFor: ['Bathing is not listed for this experience.'],
    pickupAreas: ['old_city', 'nimman', 'riverside', 'night_bazaar', 'not_sure'],
    priceLevel: 'mid',
    bookingHandoffUrl: `${BOOKING_CHANNEL_BASE}/1236820`,
  },
  {
    source: 'bokun_owner_managed',
    bokunId: '1236830',
    title: 'Day for Elephant & Bamboo Rafting Adventure Meets Natural Beauty',
    campName: 'Big Boy Elephant Sanctuary Chiang Mai',
    city: 'Chiang Mai',
    category: 'local_experience',
    durationType: 'full_day',
    kidFriendlyScore: 4,
    ethicalScore: 3,
    elephantInteractionLevel: 3,
    foodOrCookingFocus: true,
    natureFocus: true,
    bathingAvailable: false,
    feedingAvailable: false,
    walkingAvailable: false,
    photoFriendly: true,
    transferConvenienceScore: 3,
    physicalIntensity: 'medium',
    bestFor: ['Bamboo rafting', 'Natural scenery', 'Mixed local experience'],
    notIdealFor: ['Bathing is not listed for this experience.'],
    pickupAreas: ['old_city', 'nimman', 'riverside', 'night_bazaar', 'not_sure'],
    priceLevel: 'mid',
    bookingHandoffUrl: `${BOOKING_CHANNEL_BASE}/1236830`,
  },
]
