export type GlobalDestination = {
  slug: string
  name: string
  region: string
  heroTitle: string
  shortDescription: string
  topCities: string[]
  popularTourTypes: string[]
  recommendedDays: string
  bestTimeToVisit: string
  hasLiveInventory: boolean
  comingSoon: boolean
  worldCup2026Relevant: boolean
}

export const globalDestinations: GlobalDestination[] = [
  {
    slug: 'united-states',
    name: 'United States',
    region: 'North America',
    heroTitle: 'AI travel planning for America’s biggest city trips',
    shortDescription: 'Plan World Cup travel, city breaks, food routes, airport transfers, and private day trips across major U.S. gateways.',
    topCities: ['New York / New Jersey', 'Los Angeles', 'Miami', 'Dallas', 'Seattle', 'San Francisco', 'Las Vegas', 'Orlando'],
    popularTourTypes: ['World Cup transfers', 'City highlights', 'Food tours', 'Private drivers', 'Theme park days'],
    recommendedDays: '5-10 days',
    bestTimeToVisit: 'Spring and fall for city travel; June-July 2026 for World Cup trips.',
    hasLiveInventory: false,
    comingSoon: true,
    worldCup2026Relevant: true,
  },
  {
    slug: 'canada',
    name: 'Canada',
    region: 'North America',
    heroTitle: 'Canada city routes, nature escapes, and World Cup travel planning',
    shortDescription: 'Build Toronto, Vancouver, and Montreal routes with city highlights, food experiences, and future partner tours.',
    topCities: ['Toronto', 'Vancouver', 'Montreal'],
    popularTourTypes: ['World Cup transfers', 'City highlights', 'Nature day trips', 'Food experiences', 'Private tours'],
    recommendedDays: '5-8 days',
    bestTimeToVisit: 'May through October for city and nature routes; summer 2026 for World Cup travel.',
    hasLiveInventory: false,
    comingSoon: true,
    worldCup2026Relevant: true,
  },
  {
    slug: 'mexico',
    name: 'Mexico',
    region: 'North America',
    heroTitle: 'Mexico travel planning for culture, food, coast, and World Cup cities',
    shortDescription: 'Plan Mexico City, Guadalajara, Monterrey, and Cancun routes with culture, stadium logistics, and day trips.',
    topCities: ['Mexico City', 'Guadalajara', 'Monterrey', 'Cancun'],
    popularTourTypes: ['World Cup transfers', 'Food tours', 'Archaeology day trips', 'Private drivers', 'City highlights'],
    recommendedDays: '5-9 days',
    bestTimeToVisit: 'November through April for comfortable weather; June-July 2026 for World Cup trips.',
    hasLiveInventory: false,
    comingSoon: true,
    worldCup2026Relevant: true,
  },
  {
    slug: 'italy',
    name: 'Italy',
    region: 'Europe',
    heroTitle: 'Italy day tours for first-time routes and food-led city breaks',
    shortDescription: 'Shape Rome, Florence, Venice, Naples, and Milan into realistic routes with culture, food, and countryside day tours.',
    topCities: ['Rome', 'Florence', 'Venice', 'Naples', 'Milan'],
    popularTourTypes: ['Historic city walks', 'Food tours', 'Wine regions', 'Museum routes', 'Private drivers'],
    recommendedDays: '7-12 days',
    bestTimeToVisit: 'April-June and September-October for lighter crowds and better walking weather.',
    hasLiveInventory: false,
    comingSoon: true,
    worldCup2026Relevant: false,
  },
  {
    slug: 'france',
    name: 'France',
    region: 'Europe',
    heroTitle: 'France itineraries with smart day tour matching',
    shortDescription: 'Plan Paris, Nice, Lyon, and Marseille routes with museums, food, wine regions, and private day trips.',
    topCities: ['Paris', 'Nice', 'Lyon', 'Marseille'],
    popularTourTypes: ['Museum routes', 'Wine day trips', 'Food tours', 'Coastal drives', 'Private city highlights'],
    recommendedDays: '5-10 days',
    bestTimeToVisit: 'April-June and September-October for balanced weather and availability.',
    hasLiveInventory: false,
    comingSoon: true,
    worldCup2026Relevant: false,
  },
  {
    slug: 'united-kingdom',
    name: 'United Kingdom',
    region: 'Europe',
    heroTitle: 'United Kingdom routes for history, football cities, and countryside days',
    shortDescription: 'Build London, Edinburgh, Liverpool, and Manchester plans with castles, museums, pubs, and private touring options.',
    topCities: ['London', 'Edinburgh', 'Liverpool', 'Manchester'],
    popularTourTypes: ['Historic walks', 'Castle day trips', 'Football city routes', 'Food and pub tours', 'Private drivers'],
    recommendedDays: '5-9 days',
    bestTimeToVisit: 'May-September for longer days; December for festive city breaks.',
    hasLiveInventory: false,
    comingSoon: true,
    worldCup2026Relevant: false,
  },
  {
    slug: 'spain',
    name: 'Spain',
    region: 'Europe',
    heroTitle: 'Spain day tour planning for culture, food, and southern routes',
    shortDescription: 'Compare Barcelona, Madrid, Seville, and Granada routes with tapas, art, architecture, and private day trips.',
    topCities: ['Barcelona', 'Madrid', 'Seville', 'Granada'],
    popularTourTypes: ['Architecture routes', 'Tapas tours', 'Flamenco evenings', 'Historic day trips', 'Private city tours'],
    recommendedDays: '7-10 days',
    bestTimeToVisit: 'April-June and September-November for comfortable city travel.',
    hasLiveInventory: false,
    comingSoon: true,
    worldCup2026Relevant: false,
  },
  {
    slug: 'portugal',
    name: 'Portugal',
    region: 'Europe',
    heroTitle: 'Portugal routes for Lisbon, Porto, Sintra, coast, and wine',
    shortDescription: 'Plan Lisbon, Porto, and Sintra with food experiences, coastal routes, wine valleys, and private touring days.',
    topCities: ['Lisbon', 'Porto', 'Sintra'],
    popularTourTypes: ['Food tours', 'Wine day trips', 'Coastal drives', 'Historic walks', 'Private transfers'],
    recommendedDays: '5-8 days',
    bestTimeToVisit: 'March-June and September-October for milder weather and strong value.',
    hasLiveInventory: false,
    comingSoon: true,
    worldCup2026Relevant: false,
  },
  {
    slug: 'germany',
    name: 'Germany',
    region: 'Europe',
    heroTitle: 'Germany city routes, castles, beer halls, and private day trips',
    shortDescription: 'Build Berlin, Munich, Hamburg, and Frankfurt routes with history, castles, food, and efficient train-based planning.',
    topCities: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt'],
    popularTourTypes: ['Castle day trips', 'History tours', 'Beer and food routes', 'Museum days', 'Private drivers'],
    recommendedDays: '5-9 days',
    bestTimeToVisit: 'May-October for city and countryside routes; December for Christmas markets.',
    hasLiveInventory: false,
    comingSoon: true,
    worldCup2026Relevant: false,
  },
  {
    slug: 'austria',
    name: 'Austria',
    region: 'Europe',
    heroTitle: 'Austria day tour planning for Vienna, Salzburg, Hallstatt, and alpine routes',
    shortDescription: 'Design elegant Austria routes with palaces, classical music, lake towns, alpine scenery, and private touring days.',
    topCities: ['Vienna', 'Salzburg', 'Hallstatt', 'Innsbruck'],
    popularTourTypes: ['Palace routes', 'Lake town day trips', 'Classical music evenings', 'Alpine drives', 'Private tours'],
    recommendedDays: '4-7 days',
    bestTimeToVisit: 'April-June and September-October for city comfort; winter for festive alpine routes.',
    hasLiveInventory: false,
    comingSoon: true,
    worldCup2026Relevant: false,
  },
  {
    slug: 'netherlands',
    name: 'Netherlands',
    region: 'Europe',
    heroTitle: 'Netherlands city and countryside routes from Amsterdam to Rotterdam',
    shortDescription: 'Plan canal routes, museums, cycling-friendly days, windmills, food, and future private partner tours.',
    topCities: ['Amsterdam', 'Rotterdam'],
    popularTourTypes: ['Canal routes', 'Museum days', 'Cycling tours', 'Windmill day trips', 'Food experiences'],
    recommendedDays: '3-6 days',
    bestTimeToVisit: 'April-May for tulips; June-September for city and countryside touring.',
    hasLiveInventory: false,
    comingSoon: true,
    worldCup2026Relevant: false,
  },
  {
    slug: 'greece',
    name: 'Greece',
    region: 'Europe',
    heroTitle: 'Greece routes for Athens, islands, archaeology, and private sea days',
    shortDescription: 'Shape Athens, Santorini, Mykonos, and Crete plans with history, island hopping, food, and private boat options.',
    topCities: ['Athens', 'Santorini', 'Mykonos', 'Crete'],
    popularTourTypes: ['Archaeology tours', 'Island hopping', 'Boat days', 'Food routes', 'Private transfers'],
    recommendedDays: '6-10 days',
    bestTimeToVisit: 'May-June and September-October for islands with fewer crowds.',
    hasLiveInventory: false,
    comingSoon: true,
    worldCup2026Relevant: false,
  },
  {
    slug: 'switzerland',
    name: 'Switzerland',
    region: 'Europe',
    heroTitle: 'Switzerland day tour planning for lakes, mountains, and scenic rail routes',
    shortDescription: 'Plan Zurich, Lucerne, Interlaken, and Geneva with alpine viewpoints, lake towns, and efficient scenic transfers.',
    topCities: ['Zurich', 'Lucerne', 'Interlaken', 'Geneva'],
    popularTourTypes: ['Mountain day trips', 'Scenic rail routes', 'Lake cruises', 'Private drivers', 'Food experiences'],
    recommendedDays: '5-8 days',
    bestTimeToVisit: 'June-September for mountains and lakes; December-March for winter scenery.',
    hasLiveInventory: false,
    comingSoon: true,
    worldCup2026Relevant: false,
  },
  {
    slug: 'japan',
    name: 'Japan',
    region: 'Asia',
    heroTitle: 'Japan planning for Tokyo, Kyoto, Osaka, Hiroshima, and Mount Fuji',
    shortDescription: 'Build first-time Japan routes with temples, food, neighborhoods, bullet-train days, and future partner-led experiences.',
    topCities: ['Tokyo', 'Kyoto', 'Osaka', 'Hiroshima', 'Mount Fuji'],
    popularTourTypes: ['Food walks', 'Temple routes', 'Private guides', 'Mount Fuji day trips', 'Cultural workshops'],
    recommendedDays: '7-14 days',
    bestTimeToVisit: 'March-April for cherry blossoms; October-November for autumn colors.',
    hasLiveInventory: false,
    comingSoon: true,
    worldCup2026Relevant: false,
  },
  {
    slug: 'thailand',
    name: 'Thailand',
    region: 'Asia',
    heroTitle: 'Thailand is RadarScout’s first live partner-tour destination',
    shortDescription: 'Explore real Bókun-supplied partner tours across Bangkok, Chiang Mai, Phuket, Pattaya, Krabi, and Koh Samui.',
    topCities: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Krabi', 'Koh Samui'],
    popularTourTypes: ['Island tours', 'Elephant care', 'Temple routes', 'Food experiences', 'Airport transfers', 'Private tours'],
    recommendedDays: '5-10 days',
    bestTimeToVisit: 'November-February for the driest weather; shoulder months for better value.',
    hasLiveInventory: true,
    comingSoon: false,
    worldCup2026Relevant: false,
  },
]

export function getGlobalDestination(slug: string): GlobalDestination | undefined {
  return globalDestinations.find(destination => destination.slug === slug)
}

export function liveInventoryDestinations(): GlobalDestination[] {
  return globalDestinations.filter(destination => destination.hasLiveInventory)
}

export function comingSoonDestinations(): GlobalDestination[] {
  return globalDestinations.filter(destination => destination.comingSoon)
}
