ALTER TYPE "Platform" ADD VALUE IF NOT EXISTS 'X';
ALTER TYPE "Platform" ADD VALUE IF NOT EXISTS 'QUORA';
ALTER TYPE "Platform" ADD VALUE IF NOT EXISTS 'RSS';
ALTER TYPE "Platform" ADD VALUE IF NOT EXISTS 'FORUM';

ALTER TABLE "Match"
ADD COLUMN "location" TEXT,
ADD COLUMN "contentCategory" TEXT,
ADD COLUMN "travelIntentScore" INTEGER,
ADD COLUMN "credibilityScore" INTEGER,
ADD COLUMN "commercialScore" INTEGER,
ADD COLUMN "sourceMeta" JSONB NOT NULL DEFAULT '{}';
