#!/usr/bin/env python3
import json, os

PRODUCTS = [
    {"slug": "xiaomi-band-8", "name": "Xiaomi Smart Band 8", "brand": "Xiaomi", "category": "Fitness Band", "summary": "Ultra-affordable fitness band with AMOLED display and comprehensive tracking.", "priceRange": "$", "officialUrl": "https://mi.com", "releaseYear": 2024, "ecosystems": ["iOS", "Android"], "connectivity": ["Bluetooth"], "sensors": ["Heart rate", "SpO2"], "features": ["AMOLED display", "150+ sports modes", "Sleep tracking", "5ATM waterproof"], "subscriptionRequired": False, "batteryLife": "Up to 16 days", "pros": ["Extremely affordable", "Excellent battery", "Bright display", "Lightweight"], "cons": ["Basic smart features", "Limited third-party apps", "GPS via phone only"], "bestFor": ["Budget buyers", "Basic tracking", "First-time wearable users"], "notBestFor": ["Advanced athletes", "Standalone GPS needs"], "alternatives": ["fitbit-charge-6", "garmin-vivosmart-5"], "affiliateLinks": [{"label": "Check price on Amazon", "merchant": "Amazon", "region": "US", "url": "", "isAffiliate": True}], "sources": [{"title": "Official", "url": "https://mi.com"}], "lastUpdated": "2026-05-19"},
    
    {"slug": "lifx-color-a19", "name": "LIFX Color A19", "brand": "LIFX", "category": "Smart Lighting", "summary": "WiFi smart bulb with vibrant colors, no hub required.", "priceRange": "$$", "officialUrl": "https://lifx.com", "releaseYear": 2023, "ecosystems": ["Matter", "HomeKit", "Alexa", "Google Home"], "connectivity": ["Wi-Fi"], "sensors": [], "features": ["16M colors", "No hub needed", "Matter support", "Extremely bright"], "subscriptionRequired": False, "batteryLife": "N/A", "pros": ["No hub required", "Very bright", "Excellent colors", "Matter certified"], "cons": ["Expensive per bulb", "WiFi only", "Larger bulb size"], "bestFor": ["No hub preference", "Maximum brightness", "HomeKit users"], "notBestFor": ["Budget lighting", "Bridge-based systems"], "alternatives": ["philips-hue-starter-kit", "nanoleaf-shapes", "wyze-bulbs"], "affiliateLinks": [{"label": "Check price on Amazon", "merchant": "Amazon", "region": "US", "url": "", "isAffiliate": True}], "sources": [{"title": "Official", "url": "https://lifx.com"}], "lastUpdated": "2026-05-19"},
    
    {"slug": "aqara-hub-m2", "name": "Aqara Hub M2", "brand": "Aqara", "category": "Smart Home Hub", "summary": "Affordable Zigbee 3.0 hub with HomeKit integration and IR control.", "priceRange": "$", "officialUrl": "https://aqara.com", "releaseYear": 2023, "ecosystems": ["HomeKit", "Alexa", "Google Home"], "connectivity": ["Ethernet", "Zigbee", "IR"], "sensors": [], "features": ["Zigbee 3.0", "IR blaster", "HomeKit support", "Alarm siren"], "subscriptionRequired": False, "batteryLife": "N/A", "pros": ["Very affordable", "HomeKit native", "IR control", "Built-in siren"], "cons": ["Requires ethernet", "Limited to Aqara ecosystem", "Basic UI"], "bestFor": ["Budget HomeKit", "Aqara device users", "IR control needs"], "notBestFor": ["WiFi-only setups", "Non-Aqara devices"], "alternatives": ["hubitat-elevation", "smartthings-hub", "homey-pro"], "affiliateLinks": [{"label": "Check price on Amazon", "merchant": "Amazon", "region": "US", "url": "", "isAffiliate": True}], "sources": [{"title": "Official", "url": "https://aqara.com"}], "lastUpdated": "2026-05-19"},
    
    {"slug": "ecovacs-deebot-x2", "name": "ECOVACS DEEBOT X2 OMNI", "brand": "ECOVACS", "category": "Robot Vacuum", "summary": "Square-shaped robot vacuum with powerful suction and auto-maintenance station.", "priceRange": "$$$$", "officialUrl": "https://ecovacs.com", "releaseYear": 2024, "ecosystems": ["iOS", "Android", "Alexa", "Google Home"], "connectivity": ["Wi-Fi"], "sensors": ["AIVI 3D", "LiDAR"], "features": ["Square design", "8000Pa suction", "Auto-empty", "Hot water mopping"], "subscriptionRequired": False, "batteryLife": "Up to 210 mins", "pros": ["Square shape for corners", "Powerful suction", "Hot water mop cleaning", "Advanced AI"], "cons": ["Very expensive", "Large dock", "Noisy"], "bestFor": ["Corner cleaning", "Tile/hardwood floors", "Hands-off maintenance"], "notBestFor": ["Budget buyers", "Small spaces"], "alternatives": ["roborock-s8-pro-ultra", "irobot-roomba-j9", "dreame-l10s-ultra"], "affiliateLinks": [{"label": "Check price on Amazon", "merchant": "Amazon", "region": "US", "url": "", "isAffiliate": True}], "sources": [{"title": "Official", "url": "https://ecovacs.com"}], "lastUpdated": "2026-05-19"}
]

output_dir = "content/products"
for p in PRODUCTS:
    with open(os.path.join(output_dir, f"{p['slug']}.json"), 'w') as f:
        json.dump(p, f, indent=2)
    print(f"✓ {p['name']}")

files = [f for f in os.listdir(output_dir) if f.endswith('.json')]
print(f"\n✅ Total: {len(files)} products now!")
